version: '3'
services:
  dbservice:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Rockstone@123$
      - MYSQL_USER=root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bootapp

  appservice:
    build: ./boot
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/personalized_data_api?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=Rockstone@123$
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
      - spring.jpa.hibernate.ddl-auto=update
    ports:
      - "8081:8080"
    networks:
      - bootapp

networks:
  bootapp:
